apiVersion: v1
kind: Service
metadata:
  name: gdp-backend-service
  namespace: default
spec:
  selector:
    app: gdp-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080