apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gdp-host-pvc
spec:
  volumeName: gdp-host-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests: 
      storage: 5Gi