apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: qdrant
  ports:
    - protocol: TCP
      port: 6333
      targetPort: 6333
