apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-host-pvc
spec:
  volumeName: qdrant-host-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests: 
      storage: 2Gi