apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-host-pv
spec:
  capacity: 
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /gdp-data
    type: DirectoryOrCreate